import { RoleDutyProfile } from './types';
import { Duty } from '../../types';

export const ROLE_DUTY_PROFILES: RoleDutyProfile[] = [
  // =========================================================================
  // 1. GOALKEEPER ROLES
  // =========================================================================
  {
    id: 'gk_defend',
    roleId: 'gk',
    roleName: 'Goalkeeper',
    code: 'GK',
    duty: 'Defend',
    compatiblePositions: ['GK'],
    keyAttributes: ['reflexes', 'handling', 'oneOnOnes', 'positioning'],
    desirableAttributes: ['aerialReach', 'commandOfArea', 'communication', 'kicking'],
    movement: {
      width: 'normal',
      depth: 'stay_back',
      lateralMovement: 'disciplined',
      roaming: false,
      boxRuns: 'never',
    },
    possession: {
      passingRisk: 'fewer_risky_passes',
      progressionRole: 'build_up_outlet',
      carrying: 'dribble_less',
      crossing: 'standard',
      ballAttraction: 'neutral',
    },
    defensive: {
      pressingIntensity: 'less_often',
      screening: 'none',
      marking: 'zonal',
      recoveryTrackback: 'low',
      aerialCover: true,
    },
    transition: {
      offensiveTransition: 'hold_shape',
      defensiveTransition: 'rest_defence_cover',
    },
    lockedPIs: ['fewer_risky_passes'],
    allowedPIs: [],
    incompatiblePIs: ['take_more_risks', 'dribble_more', 'shoot_more_often'],
    description: 'Kiper tradisional yang fokus murni menjaga garis gawang dan meminimalkan risiko operan.',
  },
  {
    id: 'sk_defend',
    roleId: 'sk',
    roleName: 'Sweeper Keeper',
    code: 'SK',
    duty: 'Defend',
    compatiblePositions: ['GK'],
    keyAttributes: ['reflexes', 'oneOnOnes', 'rushingOut', 'positioning', 'anticipation'],
    desirableAttributes: ['passing', 'composure', 'kicking', 'decisions', 'vision'],
    movement: {
      width: 'normal',
      depth: 'balanced',
      lateralMovement: 'disciplined',
      roaming: false,
      boxRuns: 'never',
    },
    possession: {
      passingRisk: 'standard',
      progressionRole: 'build_up_outlet',
      carrying: 'dribble_less',
      crossing: 'standard',
      ballAttraction: 'distributor',
    },
    defensive: {
      pressingIntensity: 'standard',
      screening: 'none',
      marking: 'zonal',
      recoveryTrackback: 'low',
      aerialCover: true,
    },
    transition: {
      offensiveTransition: 'playmaker_conduit',
      defensiveTransition: 'rest_defence_cover',
    },
    lockedPIs: [],
    allowedPIs: ['take_more_risks'],
    incompatiblePIs: ['dribble_more', 'shoot_more_often'],
    description: 'Kiper modern yang menyapu bola di belakang garis pertahanan tinggi dengan operan aman.',
  },
  {
    id: 'sk_support',
    roleId: 'sk',
    roleName: 'Sweeper Keeper',
    code: 'SK',
    duty: 'Support',
    compatiblePositions: ['GK'],
    keyAttributes: ['rushingOut', 'reflexes', 'passing', 'composure', 'anticipation', 'kicking'],
    desirableAttributes: ['firstTouch', 'vision', 'decisions', 'oneOnOnes', 'aerialReach'],
    movement: {
      width: 'normal',
      depth: 'balanced',
      lateralMovement: 'channel_runner',
      roaming: false,
      boxRuns: 'never',
    },
    possession: {
      passingRisk: 'take_more_risks',
      progressionRole: 'build_up_outlet',
      carrying: 'standard',
      crossing: 'standard',
      ballAttraction: 'distributor',
    },
    defensive: {
      pressingIntensity: 'standard',
      screening: 'none',
      marking: 'zonal',
      recoveryTrackback: 'low',
      aerialCover: true,
    },
    transition: {
      offensiveTransition: 'playmaker_conduit',
      defensiveTransition: 'rest_defence_cover',
    },
    lockedPIs: ['take_more_risks'],
    allowedPIs: [],
    incompatiblePIs: ['fewer_risky_passes', 'shoot_more_often'],
    description: 'Aktif maju keluar kotak penalti untuk memulai serangan balik cepat dan menjadi opsi passing build-up.',
  },

  // =========================================================================
  // 2. CENTRAL DEFENDER ROLES
  // =========================================================================
  {
    id: 'cd_defend',
    roleId: 'cd',
    roleName: 'Central Defender',
    code: 'CD',
    duty: 'Defend',
    compatiblePositions: ['DC'],
    keyAttributes: ['tackling', 'marking', 'heading', 'positioning', 'jumpingReach', 'strength'],
    desirableAttributes: ['bravery', 'composure', 'concentration', 'pace'],
    movement: {
      width: 'normal',
      depth: 'stay_back',
      lateralMovement: 'disciplined',
      roaming: false,
      boxRuns: 'never',
    },
    possession: {
      passingRisk: 'fewer_risky_passes',
      progressionRole: 'build_up_outlet',
      carrying: 'dribble_less',
      crossing: 'cross_less',
      ballAttraction: 'neutral',
    },
    defensive: {
      pressingIntensity: 'standard',
      screening: 'low',
      marking: 'zonal',
      recoveryTrackback: 'high',
      aerialCover: true,
    },
    transition: {
      offensiveTransition: 'hold_shape',
      defensiveTransition: 'rest_defence_cover',
    },
    lockedPIs: ['fewer_risky_passes'],
    allowedPIs: ['mark_tighter', 'sit_narrower'],
    incompatiblePIs: ['take_more_risks', 'dribble_more', 'get_further_forward', 'shoot_more_often'],
    description: 'Bek tengah murni yang menjaga garis pertahanan, memenangkan duel udara, dan mengalirkan bola sederhana.',
  },
  {
    id: 'cd_stopper',
    roleId: 'cd',
    roleName: 'Central Defender',
    code: 'CD',
    duty: 'Stopper',
    compatiblePositions: ['DC'],
    keyAttributes: ['tackling', 'heading', 'bravery', 'aggression', 'jumpingReach', 'strength'],
    desirableAttributes: ['anticipation', 'marking', 'concentration', 'positioning'],
    movement: {
      width: 'normal',
      depth: 'balanced',
      lateralMovement: 'channel_runner',
      roaming: false,
      boxRuns: 'never',
    },
    possession: {
      passingRisk: 'fewer_risky_passes',
      progressionRole: 'build_up_outlet',
      carrying: 'dribble_less',
      crossing: 'cross_less',
      ballAttraction: 'neutral',
    },
    defensive: {
      pressingIntensity: 'more_often',
      screening: 'high',
      marking: 'tight',
      recoveryTrackback: 'moderate',
      aerialCover: true,
    },
    transition: {
      offensiveTransition: 'hold_shape',
      defensiveTransition: 'counterpress_harasser',
    },
    lockedPIs: ['fewer_risky_passes', 'close_down_more'],
    allowedPIs: ['mark_tighter'],
    incompatiblePIs: ['take_more_risks', 'drop_deeper'],
    description: 'Maju agresif keluar dari garis pertahanan untuk memotong bola sebelum penyerang lawan berbalik badan.',
  },
  {
    id: 'cd_cover',
    roleId: 'cd',
    roleName: 'Central Defender',
    code: 'CD',
    duty: 'Cover',
    compatiblePositions: ['DC'],
    keyAttributes: ['anticipation', 'pace', 'acceleration', 'positioning', 'marking', 'tackling'],
    desirableAttributes: ['concentration', 'decisions', 'heading', 'jumpingReach'],
    movement: {
      width: 'normal',
      depth: 'stay_back',
      lateralMovement: 'disciplined',
      roaming: false,
      boxRuns: 'never',
    },
    possession: {
      passingRisk: 'fewer_risky_passes',
      progressionRole: 'build_up_outlet',
      carrying: 'dribble_less',
      crossing: 'cross_less',
      ballAttraction: 'neutral',
    },
    defensive: {
      pressingIntensity: 'less_often',
      screening: 'low',
      marking: 'zonal',
      recoveryTrackback: 'high',
      aerialCover: true,
    },
    transition: {
      offensiveTransition: 'hold_shape',
      defensiveTransition: 'rest_defence_cover',
    },
    lockedPIs: ['fewer_risky_passes', 'drop_deeper'],
    allowedPIs: ['sit_narrower'],
    incompatiblePIs: ['take_more_risks', 'close_down_more'],
    description: 'Turun sedikit lebih dalam untuk menyapu bola terobosan lawan dan melindungi ruang di belakang tandemnya.',
  },
  {
    id: 'bpd_defend',
    roleId: 'bpd',
    roleName: 'Ball Playing Defender',
    code: 'BPD',
    duty: 'Defend',
    compatiblePositions: ['DC'],
    keyAttributes: ['tackling', 'marking', 'passing', 'composure', 'vision', 'positioning'],
    desirableAttributes: ['technique', 'firstTouch', 'heading', 'jumpingReach', 'anticipation'],
    movement: {
      width: 'normal',
      depth: 'stay_back',
      lateralMovement: 'disciplined',
      roaming: false,
      boxRuns: 'never',
    },
    possession: {
      passingRisk: 'take_more_risks',
      progressionRole: 'progressor',
      carrying: 'standard',
      crossing: 'cross_less',
      ballAttraction: 'distributor',
    },
    defensive: {
      pressingIntensity: 'standard',
      screening: 'low',
      marking: 'zonal',
      recoveryTrackback: 'high',
      aerialCover: true,
    },
    transition: {
      offensiveTransition: 'playmaker_conduit',
      defensiveTransition: 'rest_defence_cover',
    },
    lockedPIs: ['take_more_risks'],
    allowedPIs: ['dribble_more', 'mark_tighter'],
    incompatiblePIs: ['fewer_risky_passes', 'get_further_forward', 'shoot_more_often'],
    description: 'Bek berkemampuan visi dan passing prima yang melepaskan umpan terobosan panjang langsung dari sepertiga awal.',
  },
  {
    id: 'wcb_defend',
    roleId: 'wcb',
    roleName: 'Wide Centre-Back',
    code: 'WCB',
    duty: 'Defend',
    compatiblePositions: ['DC'],
    keyAttributes: ['tackling', 'marking', 'positioning', 'pace', 'heading'],
    desirableAttributes: ['crossing', 'dribbling', 'workRate', 'stamina'],
    movement: {
      width: 'stay_wider',
      depth: 'stay_back',
      lateralMovement: 'channel_runner',
      roaming: false,
      boxRuns: 'never',
    },
    possession: {
      passingRisk: 'standard',
      progressionRole: 'build_up_outlet',
      carrying: 'standard',
      crossing: 'standard',
      ballAttraction: 'neutral',
    },
    defensive: {
      pressingIntensity: 'standard',
      screening: 'moderate',
      marking: 'tight',
      recoveryTrackback: 'high',
      aerialCover: true,
    },
    transition: {
      offensiveTransition: 'hold_shape',
      defensiveTransition: 'rest_defence_cover',
    },
    lockedPIs: ['stay_wider'],
    allowedPIs: ['take_more_risks', 'cross_aim_target_forward'],
    incompatiblePIs: ['sit_narrower'],
    description: 'Bek tengah sisi luar formasi 3-bek yang melebar untuk memberikan perlindungan flank saat transisi bertahan.',
  },
  {
    id: 'wcb_support',
    roleId: 'wcb',
    roleName: 'Wide Centre-Back',
    code: 'WCB',
    duty: 'Support',
    compatiblePositions: ['DC'],
    keyAttributes: ['tackling', 'marking', 'pace', 'crossing', 'workRate', 'stamina'],
    desirableAttributes: ['dribbling', 'passing', 'composure', 'technique'],
    movement: {
      width: 'stay_wider',
      depth: 'balanced',
      lateralMovement: 'channel_runner',
      roaming: true,
      boxRuns: 'situational',
    },
    possession: {
      passingRisk: 'standard',
      progressionRole: 'carrier',
      carrying: 'dribble_more',
      crossing: 'deep_cross',
      ballAttraction: 'neutral',
    },
    defensive: {
      pressingIntensity: 'more_often',
      screening: 'moderate',
      marking: 'zonal',
      recoveryTrackback: 'high',
      aerialCover: true,
    },
    transition: {
      offensiveTransition: 'second_wave',
      defensiveTransition: 'rest_defence_cover',
    },
    lockedPIs: ['stay_wider', 'dribble_more'],
    allowedPIs: ['cross_more_often', 'take_more_risks'],
    incompatiblePIs: ['sit_narrower', 'fewer_risky_passes'],
    description: 'Maju aktif menyisir half-space atau overlap di sisi luar untuk mengirim crossing dari kedalaman.',
  },

  // =========================================================================
  // 3. FULLBACK & WINGBACK ROLES
  // =========================================================================
  {
    id: 'fb_defend',
    roleId: 'fb',
    roleName: 'Full-Back',
    code: 'FB',
    duty: 'Defend',
    compatiblePositions: ['DR', 'DL'],
    keyAttributes: ['tackling', 'marking', 'positioning', 'anticipation', 'pace'],
    desirableAttributes: ['concentration', 'workRate', 'stamina', 'passing'],
    movement: {
      width: 'normal',
      depth: 'stay_back',
      lateralMovement: 'disciplined',
      roaming: false,
      boxRuns: 'never',
    },
    possession: {
      passingRisk: 'fewer_risky_passes',
      progressionRole: 'build_up_outlet',
      carrying: 'dribble_less',
      crossing: 'cross_less',
      ballAttraction: 'neutral',
    },
    defensive: {
      pressingIntensity: 'standard',
      screening: 'low',
      marking: 'tight',
      recoveryTrackback: 'high',
      aerialCover: false,
    },
    transition: {
      offensiveTransition: 'hold_shape',
      defensiveTransition: 'rest_defence_cover',
    },
    lockedPIs: ['fewer_risky_passes', 'cross_less_often'],
    allowedPIs: ['sit_narrower', 'stay_wider'],
    incompatiblePIs: ['get_further_forward', 'dribble_more'],
    description: 'Bek sayap konservatif yang tetap berada di garis pertahanan saat tim menyerang, menjadi pilar Rest Defence.',
  },
  {
    id: 'fb_support',
    roleId: 'fb',
    roleName: 'Full-Back',
    code: 'FB',
    duty: 'Support',
    compatiblePositions: ['DR', 'DL'],
    keyAttributes: ['tackling', 'marking', 'pace', 'workRate', 'stamina', 'crossing'],
    desirableAttributes: ['positioning', 'passing', 'teamwork', 'anticipation'],
    movement: {
      width: 'stay_wider',
      depth: 'balanced',
      lateralMovement: 'channel_runner',
      roaming: false,
      boxRuns: 'never',
    },
    possession: {
      passingRisk: 'standard',
      progressionRole: 'progressor',
      carrying: 'standard',
      crossing: 'standard',
      ballAttraction: 'neutral',
    },
    defensive: {
      pressingIntensity: 'standard',
      screening: 'low',
      marking: 'zonal',
      recoveryTrackback: 'high',
      aerialCover: false,
    },
    transition: {
      offensiveTransition: 'second_wave',
      defensiveTransition: 'regroup_fall_back',
    },
    lockedPIs: [],
    allowedPIs: ['cross_more_often', 'dribble_more', 'stay_wider'],
    incompatiblePIs: [],
    description: 'Mendukung sirkulasi bola di lini tengah dan sesekali overlap ketika ada ruang kosong di sisi sayap.',
  },
  {
    id: 'wb_attack',
    roleId: 'wb',
    roleName: 'Wing-Back',
    code: 'WB',
    duty: 'Attack',
    compatiblePositions: ['DR', 'DL', 'WBR', 'WBL'],
    keyAttributes: ['crossing', 'dribbling', 'pace', 'acceleration', 'stamina', 'workRate'],
    desirableAttributes: ['technique', 'offTheBall', 'passing', 'tackling'],
    movement: {
      width: 'hug_line',
      depth: 'get_further_forward',
      lateralMovement: 'channel_runner',
      roaming: false,
      boxRuns: 'situational',
    },
    possession: {
      passingRisk: 'standard',
      progressionRole: 'carrier',
      carrying: 'dribble_more',
      crossing: 'byline_cross',
      ballAttraction: 'neutral',
    },
    defensive: {
      pressingIntensity: 'more_often',
      screening: 'none',
      marking: 'zonal',
      recoveryTrackback: 'moderate',
      aerialCover: false,
    },
    transition: {
      offensiveTransition: 'counter_runner',
      defensiveTransition: 'regroup_fall_back',
    },
    lockedPIs: ['get_further_forward', 'dribble_more', 'stay_wider'],
    allowedPIs: ['cross_more_often', 'cross_aim_far_post'],
    incompatiblePIs: ['sit_narrower', 'fewer_risky_passes'],
    description: 'Menyisir seluruh garis tepi lapangan hingga byline untuk mengirimkan crossing berbahaya ke kotak penalti.',
  },
  {
    id: 'ifb_defend',
    roleId: 'ifb',
    roleName: 'Inverted Full-Back',
    code: 'IFB',
    duty: 'Defend',
    compatiblePositions: ['DR', 'DL'],
    keyAttributes: ['tackling', 'marking', 'positioning', 'heading', 'jumpingReach', 'pace'],
    desirableAttributes: ['strength', 'anticipation', 'composure', 'concentration'],
    movement: {
      width: 'sit_narrower',
      depth: 'stay_back',
      lateralMovement: 'disciplined',
      roaming: false,
      boxRuns: 'never',
    },
    possession: {
      passingRisk: 'fewer_risky_passes',
      progressionRole: 'build_up_outlet',
      carrying: 'dribble_less',
      crossing: 'cross_less',
      ballAttraction: 'neutral',
    },
    defensive: {
      pressingIntensity: 'standard',
      screening: 'low',
      marking: 'tight',
      recoveryTrackback: 'high',
      aerialCover: true,
    },
    transition: {
      offensiveTransition: 'hold_shape',
      defensiveTransition: 'rest_defence_cover',
    },
    lockedPIs: ['sit_narrower', 'cross_less_often', 'fewer_risky_passes'],
    allowedPIs: ['mark_tighter'],
    incompatiblePIs: ['stay_wider', 'get_further_forward', 'dribble_more'],
    description: 'Inovasi taktis FM24: Bergerak ke dalam menjadi bek tengah ke-3 saat menyerang, membentuk 3-man rest defence.',
  },
  {
    id: 'iwb_support',
    roleId: 'iwb',
    roleName: 'Inverted Wing-Back',
    code: 'IWB',
    duty: 'Support',
    compatiblePositions: ['DR', 'DL', 'WBR', 'WBL'],
    keyAttributes: ['passing', 'composure', 'tackling', 'workRate', 'stamina', 'decisions'],
    desirableAttributes: ['technique', 'vision', 'positioning', 'firstTouch'],
    movement: {
      width: 'sit_narrower',
      depth: 'balanced',
      lateralMovement: 'channel_runner',
      roaming: true,
      boxRuns: 'situational',
    },
    possession: {
      passingRisk: 'standard',
      progressionRole: 'progressor',
      carrying: 'standard',
      crossing: 'cross_less',
      ballAttraction: 'distributor',
    },
    defensive: {
      pressingIntensity: 'more_often',
      screening: 'moderate',
      marking: 'zonal',
      recoveryTrackback: 'high',
      aerialCover: false,
    },
    transition: {
      offensiveTransition: 'playmaker_conduit',
      defensiveTransition: 'counterpress_anchor',
    },
    lockedPIs: ['sit_narrower'],
    allowedPIs: ['take_more_risks', 'dribble_more'],
    incompatiblePIs: ['stay_wider', 'cross_more_often'],
    description: 'Masuk ke lini tengah membentuk double pivot saat tim menguasai bola untuk mendominasi zona sentral.',
  },

  // =========================================================================
  // 4. DEFENSIVE MIDFIELD ROLES
  // =========================================================================
  {
    id: 'anchor_defend',
    roleId: 'anchor',
    roleName: 'Anchor',
    code: 'A',
    duty: 'Defend',
    compatiblePositions: ['DM'],
    keyAttributes: ['tackling', 'marking', 'positioning', 'anticipation', 'decisions'],
    desirableAttributes: ['concentration', 'composure', 'strength', 'passing'],
    movement: {
      width: 'normal',
      depth: 'stay_back',
      lateralMovement: 'disciplined',
      roaming: false,
      boxRuns: 'never',
    },
    possession: {
      passingRisk: 'fewer_risky_passes',
      progressionRole: 'build_up_outlet',
      carrying: 'dribble_less',
      crossing: 'cross_less',
      ballAttraction: 'neutral',
    },
    defensive: {
      pressingIntensity: 'less_often',
      screening: 'anchor',
      marking: 'zonal',
      recoveryTrackback: 'high',
      aerialCover: true,
    },
    transition: {
      offensiveTransition: 'hold_shape',
      defensiveTransition: 'rest_defence_cover',
    },
    lockedPIs: ['fewer_risky_passes', 'hold_position'],
    allowedPIs: ['mark_tighter'],
    incompatiblePIs: ['get_further_forward', 'take_more_risks', 'roam_from_position', 'dribble_more'],
    description: 'Gelandang perusak murni yang tidak pernah meninggalkan posisinya di depan dua bek tengah. Jaminan Rest Defence.',
  },
  {
    id: 'half_back_defend',
    roleId: 'half_back',
    roleName: 'Half Back',
    code: 'HB',
    duty: 'Defend',
    compatiblePositions: ['DM'],
    keyAttributes: ['tackling', 'marking', 'positioning', 'composure', 'passing', 'anticipation'],
    desirableAttributes: ['heading', 'jumpingReach', 'decisions', 'vision'],
    movement: {
      width: 'normal',
      depth: 'drop_deep',
      lateralMovement: 'disciplined',
      roaming: false,
      boxRuns: 'never',
    },
    possession: {
      passingRisk: 'standard',
      progressionRole: 'build_up_outlet',
      carrying: 'dribble_less',
      crossing: 'cross_less',
      ballAttraction: 'distributor',
    },
    defensive: {
      pressingIntensity: 'standard',
      screening: 'high',
      marking: 'zonal',
      recoveryTrackback: 'high',
      aerialCover: true,
    },
    transition: {
      offensiveTransition: 'hold_shape',
      defensiveTransition: 'rest_defence_cover',
    },
    lockedPIs: ['fewer_risky_passes', 'drop_deeper'],
    allowedPIs: ['mark_tighter'],
    incompatiblePIs: ['get_further_forward', 'take_more_risks', 'dribble_more'],
    description: 'Turun ke antara dua bek tengah saat build-up, menciptakan keunggulan 3-bek dan mendorong fullback naik bebas.',
  },
  {
    id: 'dlp_dm_defend',
    roleId: 'dlp_dm',
    roleName: 'Deep Lying Playmaker',
    code: 'DLP',
    duty: 'Defend',
    compatiblePositions: ['DM'],
    keyAttributes: ['passing', 'vision', 'composure', 'technique', 'decisions', 'positioning'],
    desirableAttributes: ['tackling', 'firstTouch', 'teamwork', 'anticipation'],
    movement: {
      width: 'normal',
      depth: 'stay_back',
      lateralMovement: 'disciplined',
      roaming: false,
      boxRuns: 'never',
    },
    possession: {
      passingRisk: 'take_more_risks',
      progressionRole: 'progressor',
      carrying: 'dribble_less',
      crossing: 'cross_less',
      ballAttraction: 'magnet',
    },
    defensive: {
      pressingIntensity: 'less_often',
      screening: 'moderate',
      marking: 'zonal',
      recoveryTrackback: 'moderate',
      aerialCover: false,
    },
    transition: {
      offensiveTransition: 'playmaker_conduit',
      defensiveTransition: 'rest_defence_cover',
    },
    lockedPIs: ['take_more_risks', 'hold_position'],
    allowedPIs: ['mark_tighter'],
    incompatiblePIs: ['fewer_risky_passes', 'get_further_forward', 'dribble_more'],
    description: 'Arsitek serangan dari kedalaman yang mendikte ritme permainan sambil tetap menjaga kedisiplinan posisi.',
  },
  {
    id: 'segundo_volante_attack',
    roleId: 'segundo_volante',
    roleName: 'Segundo Volante',
    code: 'VOL',
    duty: 'Attack',
    compatiblePositions: ['DM'],
    keyAttributes: ['workRate', 'stamina', 'pace', 'tackling', 'passing', 'offTheBall', 'finishing'],
    desirableAttributes: ['longShots', 'composure', 'dribbling', 'decisions', 'anticipation'],
    movement: {
      width: 'normal',
      depth: 'get_further_forward',
      lateralMovement: 'channel_runner',
      roaming: true,
      boxRuns: 'frequent',
    },
    possession: {
      passingRisk: 'standard',
      progressionRole: 'finisher',
      carrying: 'dribble_more',
      crossing: 'standard',
      ballAttraction: 'neutral',
    },
    defensive: {
      pressingIntensity: 'more_often',
      screening: 'moderate',
      marking: 'zonal',
      recoveryTrackback: 'high',
      aerialCover: false,
    },
    transition: {
      offensiveTransition: 'counter_runner',
      defensiveTransition: 'counterpress_harasser',
    },
    lockedPIs: ['get_further_forward', 'dribble_more'],
    allowedPIs: ['shoot_more_often', 'take_more_risks'],
    incompatiblePIs: ['hold_position', 'fewer_risky_passes'],
    description: 'Senjata rahasia sistem double pivot: Bertahan saat kehilangan bola dan meledak menyerang masuk ke kotak penalti lawan.',
  },

  // =========================================================================
  // 5. CENTRAL MIDFIELD ROLES
  // =========================================================================
  {
    id: 'bbm_support',
    roleId: 'bbm',
    roleName: 'Box-to-Box Midfielder',
    code: 'BBM',
    duty: 'Support',
    compatiblePositions: ['MC'],
    keyAttributes: ['workRate', 'stamina', 'tackling', 'passing', 'offTheBall', 'positioning'],
    desirableAttributes: ['pace', 'decisions', 'finishing', 'longShots', 'technique'],
    movement: {
      width: 'normal',
      depth: 'balanced',
      lateralMovement: 'channel_runner',
      roaming: true,
      boxRuns: 'frequent',
    },
    possession: {
      passingRisk: 'standard',
      progressionRole: 'progressor',
      carrying: 'standard',
      crossing: 'standard',
      ballAttraction: 'neutral',
    },
    defensive: {
      pressingIntensity: 'more_often',
      screening: 'high',
      marking: 'zonal',
      recoveryTrackback: 'high',
      aerialCover: false,
    },
    transition: {
      offensiveTransition: 'second_wave',
      defensiveTransition: 'counterpress_harasser',
    },
    lockedPIs: [],
    allowedPIs: ['get_further_forward', 'shoot_more_often', 'dribble_more'],
    incompatiblePIs: ['hold_position'],
    description: 'Mesin tak kenal lelah yang menyambungkan kedua kotak penalti, membantu bertahan dan menyusup mencetak gol.',
  },
  {
    id: 'mezzala_attack',
    roleId: 'mezzala',
    roleName: 'Mezzala',
    code: 'MEZ',
    duty: 'Attack',
    compatiblePositions: ['MC'],
    keyAttributes: ['dribbling', 'passing', 'vision', 'technique', 'offTheBall', 'decisions'],
    desirableAttributes: ['finishing', 'acceleration', 'pace', 'composure', 'firstTouch'],
    movement: {
      width: 'stay_wider',
      depth: 'get_further_forward',
      lateralMovement: 'channel_runner',
      roaming: true,
      boxRuns: 'frequent',
    },
    possession: {
      passingRisk: 'take_more_risks',
      progressionRole: 'final_ball_creator',
      carrying: 'dribble_more',
      crossing: 'standard',
      ballAttraction: 'neutral',
    },
    defensive: {
      pressingIntensity: 'more_often',
      screening: 'low',
      marking: 'zonal',
      recoveryTrackback: 'moderate',
      aerialCover: false,
    },
    transition: {
      offensiveTransition: 'counter_runner',
      defensiveTransition: 'counterpress_harasser',
    },
    lockedPIs: ['stay_wider', 'get_further_forward', 'dribble_more'],
    allowedPIs: ['shoot_more_often', 'take_more_risks'],
    incompatiblePIs: ['sit_narrower', 'fewer_risky_passes', 'hold_position'],
    description: 'Gelandang sayap dalam (half-space specialist) yang menusuk diagonal ke ruang antara bek tengah dan fullback lawan.',
  },

  // =========================================================================
  // 6. ATTACKING MIDFIELD & WIDE ROLES
  // =========================================================================
  {
    id: 'inside_forward_attack',
    roleId: 'inside_forward',
    roleName: 'Inside Forward',
    code: 'IF',
    duty: 'Attack',
    compatiblePositions: ['AMR', 'AML'],
    keyAttributes: ['pace', 'acceleration', 'dribbling', 'finishing', 'offTheBall', 'technique'],
    desirableAttributes: ['composure', 'passing', 'vision', 'agility'],
    movement: {
      width: 'cut_inside',
      depth: 'get_further_forward',
      lateralMovement: 'channel_runner',
      roaming: true,
      boxRuns: 'primary_target',
    },
    possession: {
      passingRisk: 'take_more_risks',
      progressionRole: 'finisher',
      carrying: 'dribble_more',
      crossing: 'cross_less',
      ballAttraction: 'neutral',
    },
    defensive: {
      pressingIntensity: 'more_often',
      screening: 'none',
      marking: 'zonal',
      recoveryTrackback: 'moderate',
      aerialCover: false,
    },
    transition: {
      offensiveTransition: 'counter_runner',
      defensiveTransition: 'counterpress_harasser',
    },
    lockedPIs: ['cut_inside_with_ball', 'get_further_forward', 'dribble_more'],
    allowedPIs: ['shoot_more_often', 'roam_from_position'],
    incompatiblePIs: ['stay_wider', 'cross_more_often'],
    description: 'Penyerang sayap pencetak gol yang memotong langsung ke jantung pertahanan lawan untuk melepaskan tembakan.',
  },
  {
    id: 'winger_support',
    roleId: 'winger',
    roleName: 'Winger',
    code: 'W',
    duty: 'Support',
    compatiblePositions: ['MR', 'ML', 'AMR', 'AML'],
    keyAttributes: ['crossing', 'dribbling', 'pace', 'acceleration', 'technique'],
    desirableAttributes: ['workRate', 'stamina', 'passing', 'teamwork'],
    movement: {
      width: 'hug_line',
      depth: 'balanced',
      lateralMovement: 'disciplined',
      roaming: false,
      boxRuns: 'never',
    },
    possession: {
      passingRisk: 'standard',
      progressionRole: 'carrier',
      carrying: 'dribble_more',
      crossing: 'byline_cross',
      ballAttraction: 'neutral',
    },
    defensive: {
      pressingIntensity: 'standard',
      screening: 'low',
      marking: 'zonal',
      recoveryTrackback: 'high',
      aerialCover: false,
    },
    transition: {
      offensiveTransition: 'second_wave',
      defensiveTransition: 'regroup_fall_back',
    },
    lockedPIs: ['stay_wider', 'dribble_more'],
    allowedPIs: ['cross_more_often', 'cross_aim_far_post'],
    incompatiblePIs: ['cut_inside_with_ball', 'sit_narrower'],
    description: 'Pemain sayap klasik yang menjaga lebar lapangan dan menyuplai umpan silang akurat untuk striker.',
  },
  {
    id: 'ap_amc_support',
    roleId: 'ap_amc',
    roleName: 'Advanced Playmaker',
    code: 'AP',
    duty: 'Support',
    compatiblePositions: ['AMC'],
    keyAttributes: ['passing', 'vision', 'technique', 'composure', 'firstTouch', 'decisions'],
    desirableAttributes: ['flair', 'anticipation', 'offTheBall', 'teamwork'],
    movement: {
      width: 'normal',
      depth: 'balanced',
      lateralMovement: 'free_role',
      roaming: true,
      boxRuns: 'situational',
    },
    possession: {
      passingRisk: 'take_more_risks',
      progressionRole: 'final_ball_creator',
      carrying: 'standard',
      crossing: 'standard',
      ballAttraction: 'magnet',
    },
    defensive: {
      pressingIntensity: 'standard',
      screening: 'low',
      marking: 'zonal',
      recoveryTrackback: 'moderate',
      aerialCover: false,
    },
    transition: {
      offensiveTransition: 'playmaker_conduit',
      defensiveTransition: 'counterpress_anchor',
    },
    lockedPIs: ['take_more_risks', 'roam_from_position'],
    allowedPIs: ['dribble_more', 'shoot_less_often'],
    incompatiblePIs: ['fewer_risky_passes', 'hold_position'],
    description: 'Jantung kreativitas tim di sepertiga akhir: Mencari ruang antar lini untuk melepaskan umpan terobosan mematikan.',
  },

  // =========================================================================
  // 7. STRIKER ROLES
  // =========================================================================
  {
    id: 'af_attack',
    roleId: 'af',
    roleName: 'Advanced Forward',
    code: 'AF',
    duty: 'Attack',
    compatiblePositions: ['STC'],
    keyAttributes: ['pace', 'acceleration', 'finishing', 'offTheBall', 'composure', 'dribbling'],
    desirableAttributes: ['firstTouch', 'technique', 'anticipation', 'heading', 'jumpingReach'],
    movement: {
      width: 'stay_wider',
      depth: 'get_further_forward',
      lateralMovement: 'channel_runner',
      roaming: true,
      boxRuns: 'primary_target',
    },
    possession: {
      passingRisk: 'standard',
      progressionRole: 'finisher',
      carrying: 'dribble_more',
      crossing: 'cross_less',
      ballAttraction: 'neutral',
    },
    defensive: {
      pressingIntensity: 'more_often',
      screening: 'none',
      marking: 'zonal',
      recoveryTrackback: 'low',
      aerialCover: false,
    },
    transition: {
      offensiveTransition: 'counter_runner',
      defensiveTransition: 'counterpress_harasser',
    },
    lockedPIs: ['get_further_forward', 'dribble_more', 'move_into_channels'],
    allowedPIs: ['shoot_more_often', 'roam_from_position'],
    incompatiblePIs: ['fewer_risky_passes', 'hold_position'],
    description: 'Ujung tombak paling serba bisa di FM24: Berlari ke celah bek, mendribel, dan menyelesaikan peluang dengan dingin.',
  },
  {
    id: 'dlf_support',
    roleId: 'dlf',
    roleName: 'Deep Lying Forward',
    code: 'DLF',
    duty: 'Support',
    compatiblePositions: ['STC'],
    keyAttributes: ['passing', 'vision', 'firstTouch', 'technique', 'teamwork', 'strength'],
    desirableAttributes: ['composure', 'finishing', 'anticipation', 'decisions', 'offTheBall'],
    movement: {
      width: 'normal',
      depth: 'drop_deep',
      lateralMovement: 'disciplined',
      roaming: false,
      boxRuns: 'situational',
    },
    possession: {
      passingRisk: 'take_more_risks',
      progressionRole: 'final_ball_creator',
      carrying: 'standard',
      crossing: 'standard',
      ballAttraction: 'distributor',
    },
    defensive: {
      pressingIntensity: 'standard',
      screening: 'low',
      marking: 'zonal',
      recoveryTrackback: 'moderate',
      aerialCover: false,
    },
    transition: {
      offensiveTransition: 'playmaker_conduit',
      defensiveTransition: 'regroup_fall_back',
    },
    lockedPIs: ['fewer_risky_passes'],
    allowedPIs: ['take_more_risks', 'shoot_less_often'],
    incompatiblePIs: ['get_further_forward'],
    description: 'Turun ke lini tengah menjemput bola, memancing bek lawan keluar, dan menyuplai bola ke sayap atau gelandang kedua.',
  },
  {
    id: 'tf_attack',
    roleId: 'tf',
    roleName: 'Target Forward',
    code: 'TF',
    duty: 'Attack',
    compatiblePositions: ['STC'],
    keyAttributes: ['heading', 'jumpingReach', 'strength', 'bravery', 'finishing'],
    desirableAttributes: ['balance', 'firstTouch', 'composure', 'teamwork'],
    movement: {
      width: 'normal',
      depth: 'get_further_forward',
      lateralMovement: 'disciplined',
      roaming: false,
      boxRuns: 'primary_target',
    },
    possession: {
      passingRisk: 'fewer_risky_passes',
      progressionRole: 'finisher',
      carrying: 'dribble_less',
      crossing: 'cross_less',
      ballAttraction: 'magnet',
    },
    defensive: {
      pressingIntensity: 'standard',
      screening: 'none',
      marking: 'zonal',
      recoveryTrackback: 'low',
      aerialCover: true,
    },
    transition: {
      offensiveTransition: 'counter_runner',
      defensiveTransition: 'counterpress_anchor',
    },
    lockedPIs: ['hold_up_ball', 'get_further_forward'],
    allowedPIs: ['shoot_more_often'],
    incompatiblePIs: ['dribble_more', 'move_into_channels', 'roam_from_position'],
    description: 'Monster fisik di udara yang menjadi muara umpan silang dan bola mati, menahan bola untuk rekan di kotak penalti.',
  },
];

// Helper lookup
export function getRoleDutyProfile(roleId: string, duty: Duty): RoleDutyProfile | undefined {
  // First try exact profile id: e.g. "bpd_defend"
  const exactKey = `${roleId}_${duty.toLowerCase()}`;
  const found = ROLE_DUTY_PROFILES.find(p => p.id === exactKey);
  if (found) return found;

  // Fallback match roleId and allowed duty
  return ROLE_DUTY_PROFILES.find(p => p.roleId === roleId && (p.duty === duty || p.duty === 'Support'));
}

export function getAllRoleDutyProfiles(): RoleDutyProfile[] {
  return ROLE_DUTY_PROFILES;
}

export function isRoleDutyCompatible(roleId: string, duty: Duty): boolean {
  return !!getRoleDutyProfile(roleId, duty);
}
