import { RoleDefinition } from '../types';

export const ALL_ROLES: RoleDefinition[] = [
  // ================= GOALKEEPERS =================
  {
    id: 'gk',
    name: 'Goalkeeper',
    code: 'GK',
    position: 'GK',
    availableDuties: ['Defend'],
    keyAttributes: ['reflexes', 'handling', 'aerialReach', 'positioning', 'communication'],
    desirableAttributes: ['oneOnOnes', 'commandOfArea', 'kicking', 'throwing', 'agility', 'concentration', 'decisions'],
    hardcodedPIs: ['fewer_risky_passes', 'hold_position'],
    incompatiblePIs: ['take_more_risks', 'dribble_more'],
    description: 'Kiper tradisional yang fokus pada penyelamatan garis gawang dan membuang bola dengan aman.',
  },
  {
    id: 'sk',
    name: 'Sweeper Keeper',
    code: 'SK',
    position: 'GK',
    availableDuties: ['Defend', 'Support', 'Attack'],
    keyAttributes: ['reflexes', 'rushingOut', 'anticipation', 'positioning', 'composure', 'kicking', 'oneOnOnes'],
    desirableAttributes: ['passing', 'vision', 'pace', 'acceleration', 'agility', 'decisions', 'firstTouch'],
    hardcodedPIs: ['take_more_risks'],
    incompatiblePIs: ['fewer_risky_passes', 'hold_position'],
    description: 'Kiper modern yang aktif keluar dari kotak penalti untuk menyapu bola terobosan di belakang high line.',
  },

  // ================= CENTRAL DEFENDERS =================
  {
    id: 'cd',
    name: 'Central Defender',
    code: 'CD',
    position: 'DC',
    availableDuties: ['Defend', 'Stopper', 'Cover'],
    keyAttributes: ['tackling', 'marking', 'heading', 'positioning', 'jumpingReach', 'strength'],
    desirableAttributes: ['anticipation', 'bravery', 'concentration', 'decisions', 'pace', 'composure'],
    hardcodedPIs: ['hold_position', 'fewer_risky_passes'],
    incompatiblePIs: ['take_more_risks', 'dribble_more', 'roam_from_position'],
    description: 'Bek tengah konvensional; memenangkan duel fisik dan merebut bola tanpa mengambil risiko operan rumit.',
  },
  {
    id: 'bpd',
    name: 'Ball Playing Defender',
    code: 'BPD',
    position: 'DC',
    availableDuties: ['Defend', 'Stopper', 'Cover'],
    keyAttributes: ['tackling', 'marking', 'heading', 'positioning', 'passing', 'composure', 'decisions', 'jumpingReach', 'strength'],
    desirableAttributes: ['vision', 'technique', 'firstTouch', 'anticipation', 'bravery', 'pace'],
    hardcodedPIs: ['take_more_risks'],
    incompatiblePIs: ['fewer_risky_passes'],
    description: 'Bek tengah inisiator serangan; mendistribusikan bola panjang/terobosan vertikal dari garis belakang.',
  },
  {
    id: 'ncb',
    name: 'No-Nonsense Centre-Back',
    code: 'NCB',
    position: 'DC',
    availableDuties: ['Defend', 'Stopper', 'Cover'],
    keyAttributes: ['tackling', 'marking', 'heading', 'positioning', 'jumpingReach', 'strength', 'bravery'],
    desirableAttributes: ['concentration', 'aggression', 'anticipation', 'pace'],
    hardcodedPIs: ['fewer_risky_passes', 'shoot_less_often', 'dribble_less', 'hold_position'],
    incompatiblePIs: ['take_more_risks', 'dribble_more', 'roam_from_position'],
    description: 'Bek murni berprinsip safety first; langsung menyapu bola jauh tanpa kompromi.',
  },
  {
    id: 'wcb',
    name: 'Wide Centre-Back',
    code: 'WCB',
    position: 'DC',
    availableDuties: ['Defend', 'Support', 'Attack'],
    keyAttributes: ['tackling', 'marking', 'heading', 'positioning', 'decisions', 'pace', 'jumpingReach', 'strength'],
    desirableAttributes: ['passing', 'crossing', 'dribbling', 'workRate', 'stamina', 'acceleration', 'vision'],
    hardcodedPIs: ['stay_wider'],
    incompatiblePIs: ['sit_narrower', 'hold_position'],
    description: 'Bek sisi dalam formasi 3/5 bek; aktif melebar dan melakukan overlap/underlap membantu serangan.',
  },
  {
    id: 'lib',
    name: 'Libero',
    code: 'LIB',
    position: 'DC',
    availableDuties: ['Defend', 'Support'],
    keyAttributes: ['composure', 'decisions', 'passing', 'vision', 'technique', 'positioning', 'anticipation', 'tackling', 'teamwork'],
    desirableAttributes: ['firstTouch', 'marking', 'heading', 'stamina', 'pace', 'agility', 'concentration'],
    hardcodedPIs: ['take_more_risks', 'dribble_more', 'roam_from_position', 'get_further_forward'],
    incompatiblePIs: ['hold_position', 'fewer_risky_passes'],
    description: 'Sweeper jenius yang melangkah maju ke lini tengah saat menguasai bola (step into midfield).',
  },

  // ================= FULL-BACKS / WING-BACKS =================
  {
    id: 'fb',
    name: 'Full-Back',
    code: 'FB',
    position: 'DR',
    availableDuties: ['Defend', 'Support', 'Attack', 'Automatic'],
    keyAttributes: ['tackling', 'marking', 'positioning', 'anticipation', 'concentration', 'pace', 'stamina'],
    desirableAttributes: ['crossing', 'passing', 'technique', 'decisions', 'workRate'],
    hardcodedPIs: [],
    incompatiblePIs: [],
    description: 'Bek sayap konvensional yang menyeimbangkan tugas bertahan dan sesekali overlap.',
  },
  {
    id: 'wb',
    name: 'Wing-Back',
    code: 'WB',
    position: 'DR',
    availableDuties: ['Defend', 'Support', 'Attack', 'Automatic'],
    keyAttributes: ['crossing', 'dribbling', 'tackling', 'marking', 'workRate', 'stamina', 'pace', 'acceleration'],
    desirableAttributes: ['passing', 'technique', 'decisions', 'positioning', 'offTheBall'],
    hardcodedPIs: ['run_wide_with_ball', 'get_further_forward'],
    incompatiblePIs: ['hold_position'],
    description: 'Penguasa garis tepi sayap; aktif naik turun menyisir seluruh koridor sayap.',
  },
  {
    id: 'nfb',
    name: 'No-Nonsense Full-Back',
    code: 'NFB',
    position: 'DR',
    availableDuties: ['Defend'],
    keyAttributes: ['tackling', 'marking', 'positioning', 'anticipation', 'concentration', 'strength', 'pace'],
    desirableAttributes: ['heading', 'bravery', 'decisions', 'stamina'],
    hardcodedPIs: ['fewer_risky_passes', 'hold_position', 'dribble_less', 'cross_less_often'],
    incompatiblePIs: ['take_more_risks', 'get_further_forward', 'dribble_more'],
    description: 'Bek sayap murni defensif; tidak pernah maju menyerang, fokus menutup winger lawan.',
  },
  {
    id: 'cwb',
    name: 'Complete Wing-Back',
    code: 'CWB',
    position: 'DR',
    availableDuties: ['Support', 'Attack'],
    keyAttributes: ['crossing', 'dribbling', 'technique', 'firstTouch', 'passing', 'workRate', 'stamina', 'pace', 'acceleration', 'decisions'],
    desirableAttributes: ['vision', 'anticipation', 'tackling', 'marking', 'positioning', 'composure'],
    hardcodedPIs: ['roam_from_position', 'dribble_more', 'run_wide_with_ball', 'cross_more_often', 'close_down_more'],
    incompatiblePIs: ['hold_position', 'dribble_less', 'sit_narrower'],
    description: 'Bek sayap menyerang bebas; memiliki mobilitas tinggi untuk menusuk ke kotak penalti atau overlap.',
  },
  {
    id: 'iwb',
    name: 'Inverted Wing-Back',
    code: 'IWB',
    position: 'DR',
    availableDuties: ['Defend', 'Support', 'Attack'],
    keyAttributes: ['passing', 'decisions', 'composure', 'workRate', 'stamina', 'positioning', 'tackling', 'teamwork'],
    desirableAttributes: ['vision', 'technique', 'firstTouch', 'anticipation', 'pace', 'acceleration'],
    hardcodedPIs: ['sit_narrower', 'cut_inside_with_ball'],
    incompatiblePIs: ['stay_wider', 'run_wide_with_ball'],
    description: 'Bek sayap yang bergerak masuk ke lini tengah sentral saat memegang bola, menciptakan overload pivot.',
  },
  {
    id: 'ifb',
    name: 'Inverted Full-Back',
    code: 'IFB',
    position: 'DR',
    availableDuties: ['Defend'],
    keyAttributes: ['tackling', 'marking', 'positioning', 'anticipation', 'heading', 'jumpingReach', 'strength'],
    desirableAttributes: ['pace', 'decisions', 'concentration', 'passing', 'bravery'],
    hardcodedPIs: ['sit_narrower', 'hold_position', 'fewer_risky_passes', 'cross_less_often', 'dribble_less'],
    incompatiblePIs: ['stay_wider', 'get_further_forward', 'run_wide_with_ball', 'dribble_more'],
    description: 'Fitur baru FM24: bergeser ke tengah menjadi bek tengah ketiga saat menyerang. Sangat kokoh untuk rest defence.',
  },

  // ================= DEFENSIVE MIDFIELDERS =================
  {
    id: 'dm',
    name: 'Defensive Midfielder',
    code: 'DM',
    position: 'DM',
    availableDuties: ['Defend', 'Support'],
    keyAttributes: ['tackling', 'positioning', 'anticipation', 'decisions', 'teamwork', 'workRate', 'stamina'],
    desirableAttributes: ['marking', 'passing', 'composure', 'concentration', 'strength'],
    hardcodedPIs: ['hold_position'],
    incompatiblePIs: ['roam_from_position', 'get_further_forward'],
    description: 'Gelandang jangkar pelindung lini belakang; menutup ruang antarlini dan mengalirkan bola sederhana.',
  },
  {
    id: 'dlp_dm',
    name: 'Deep Lying Playmaker',
    code: 'DLP',
    position: 'DM',
    availableDuties: ['Defend', 'Support'],
    keyAttributes: ['passing', 'vision', 'composure', 'decisions', 'technique', 'teamwork', 'firstTouch'],
    desirableAttributes: ['positioning', 'anticipation', 'tackling', 'concentration'],
    hardcodedPIs: ['take_more_risks', 'hold_position'],
    incompatiblePIs: ['fewer_risky_passes', 'roam_from_position'],
    description: 'Pengatur ritme dari kedalaman; mendistribusikan bola matang ke lini depan layaknya quarterback.',
  },
  {
    id: 'bwm_dm',
    name: 'Ball Winning Midfielder',
    code: 'BWM',
    position: 'DM',
    availableDuties: ['Defend', 'Support'],
    keyAttributes: ['tackling', 'aggression', 'bravery', 'workRate', 'stamina', 'teamwork', 'anticipation', 'strength'],
    desirableAttributes: ['positioning', 'marking', 'decisions', 'acceleration', 'pace'],
    hardcodedPIs: ['close_down_more', 'tackle_harder'],
    incompatiblePIs: ['ease_off_tackles', 'close_down_less'],
    description: 'Petarung agresif pemotong alur serangan lawan yang tanpa kenal lelah memburu bola.',
  },
  {
    id: 'anchor',
    name: 'Anchor',
    code: 'A',
    position: 'DM',
    availableDuties: ['Defend'],
    keyAttributes: ['positioning', 'tackling', 'marking', 'decisions', 'anticipation', 'concentration', 'strength'],
    desirableAttributes: ['teamwork', 'composure', 'passing', 'workRate'],
    hardcodedPIs: ['hold_position', 'fewer_risky_passes', 'shoot_less_often', 'dribble_less', 'mark_tighter'],
    incompatiblePIs: ['roam_from_position', 'take_more_risks', 'get_further_forward'],
    description: 'Jangkar statis yang tidak pernah meninggalkan posisinya di depan dua bek tengah.',
  },
  {
    id: 'half_back',
    name: 'Half Back',
    code: 'HB',
    position: 'DM',
    availableDuties: ['Defend'],
    keyAttributes: ['positioning', 'tackling', 'marking', 'decisions', 'anticipation', 'composure', 'teamwork'],
    desirableAttributes: ['passing', 'vision', 'concentration', 'jumpingReach', 'strength'],
    hardcodedPIs: ['hold_position', 'fewer_risky_passes'],
    incompatiblePIs: ['roam_from_position', 'get_further_forward'],
    description: 'Turun di antara dua bek tengah saat build-up sehingga kedua bek sayap bisa naik menyerang dengan aman.',
  },
  {
    id: 'regista',
    name: 'Regista',
    code: 'REG',
    position: 'DM',
    availableDuties: ['Support'],
    keyAttributes: ['passing', 'vision', 'decisions', 'composure', 'technique', 'firstTouch', 'teamwork', 'offTheBall'],
    desirableAttributes: ['anticipation', 'balance', 'agility', 'stamina'],
    hardcodedPIs: ['roam_from_position', 'take_more_risks', 'dribble_more'],
    incompatiblePIs: ['hold_position', 'fewer_risky_passes'],
    description: 'Playmaker dinamis dari kedalaman yang bebas berkeliaran mencari ruang dan mendukung serangan sepertiga akhir.',
  },
  {
    id: 'roaming_playmaker_dm',
    name: 'Roaming Playmaker',
    code: 'RPM',
    position: 'DM',
    availableDuties: ['Support'],
    keyAttributes: ['passing', 'vision', 'decisions', 'composure', 'technique', 'firstTouch', 'workRate', 'stamina', 'offTheBall', 'anticipation'],
    desirableAttributes: ['acceleration', 'pace', 'agility', 'balance', 'dribbling'],
    hardcodedPIs: ['roam_from_position', 'take_more_risks', 'dribble_more'],
    incompatiblePIs: ['hold_position'],
    description: 'Gelandang serba bisa penjelajah seluruh lapangan dengan stamina dan visi permainan tingkat tinggi.',
  },
  {
    id: 'segundo_volante',
    name: 'Segundo Volante',
    code: 'VOL',
    position: 'DM',
    availableDuties: ['Support', 'Attack'],
    keyAttributes: ['tackling', 'workRate', 'stamina', 'pace', 'acceleration', 'passing', 'offTheBall', 'decisions', 'anticipation'],
    desirableAttributes: ['finishing', 'longShots', 'composure', 'technique', 'marking', 'positioning'],
    hardcodedPIs: ['get_further_forward', 'take_more_risks', 'move_into_channels'],
    incompatiblePIs: ['hold_position', 'fewer_risky_passes'],
    description: 'Gelandang ganda yang merebut bola saat bertahan, namun melakukan sprint menusuk kotak penalti saat menyerang.',
  },

  // ================= CENTRAL MIDFIELDERS =================
  {
    id: 'cm',
    name: 'Central Midfielder',
    code: 'CM',
    position: 'MC',
    availableDuties: ['Defend', 'Support', 'Attack', 'Automatic'],
    keyAttributes: ['passing', 'decisions', 'teamwork', 'workRate', 'stamina', 'firstTouch', 'technique', 'tackling'],
    desirableAttributes: ['anticipation', 'composure', 'vision', 'positioning', 'offTheBall'],
    hardcodedPIs: [],
    incompatiblePIs: [],
    description: 'Gelandang sentral murni yang fleksibel menjalankan fungsi bertahan, menghubungkan lini, atau masuk kotak penalti.',
  },
  {
    id: 'dlp_cm',
    name: 'Deep Lying Playmaker',
    code: 'DLP',
    position: 'MC',
    availableDuties: ['Defend', 'Support'],
    keyAttributes: ['passing', 'vision', 'composure', 'decisions', 'technique', 'teamwork', 'firstTouch'],
    desirableAttributes: ['positioning', 'anticipation', 'tackling', 'concentration'],
    hardcodedPIs: ['take_more_risks', 'hold_position'],
    incompatiblePIs: ['fewer_risky_passes', 'roam_from_position'],
    description: 'Versi gelandang sentral dari DLP; mengatur tempo permainan dengan operan presisi.',
  },
  {
    id: 'bbm',
    name: 'Box-to-Box Midfielder',
    code: 'BBM',
    position: 'MC',
    availableDuties: ['Support'],
    keyAttributes: ['stamina', 'workRate', 'tackling', 'passing', 'offTheBall', 'decisions', 'teamwork', 'anticipation', 'acceleration'],
    desirableAttributes: ['finishing', 'longShots', 'technique', 'firstTouch', 'positioning', 'pace'],
    hardcodedPIs: ['get_further_forward', 'dribble_more', 'move_into_channels'],
    incompatiblePIs: ['hold_position'],
    description: 'Paru-paru tim; aktif bertahan di kotak penalti sendiri dan merangsek membantu gol di kotak penalti lawan.',
  },
  {
    id: 'bwm_cm',
    name: 'Ball Winning Midfielder',
    code: 'BWM',
    position: 'MC',
    availableDuties: ['Defend', 'Support'],
    keyAttributes: ['tackling', 'aggression', 'bravery', 'workRate', 'stamina', 'teamwork', 'anticipation'],
    desirableAttributes: ['positioning', 'marking', 'decisions', 'strength', 'acceleration'],
    hardcodedPIs: ['close_down_more', 'tackle_harder'],
    incompatiblePIs: ['ease_off_tackles'],
    description: 'Merebut bola secara agresif di sepertiga tengah lapangan.',
  },
  {
    id: 'ap_cm',
    name: 'Advanced Playmaker',
    code: 'AP',
    position: 'MC',
    availableDuties: ['Support', 'Attack'],
    keyAttributes: ['vision', 'passing', 'decisions', 'composure', 'technique', 'firstTouch', 'offTheBall', 'teamwork'],
    desirableAttributes: ['anticipation', 'dribbling', 'agility', 'balance'],
    hardcodedPIs: ['roam_from_position', 'take_more_risks'],
    incompatiblePIs: ['hold_position', 'fewer_risky_passes'],
    description: 'Mencari ruang antarlini untuk melepaskan umpan terobosan pemecah pertahanan lawan.',
  },
  {
    id: 'mezzala',
    name: 'Mezzala',
    code: 'MEZ',
    position: 'MC',
    availableDuties: ['Support', 'Attack'],
    keyAttributes: ['passing', 'vision', 'technique', 'offTheBall', 'decisions', 'workRate', 'acceleration'],
    desirableAttributes: ['dribbling', 'firstTouch', 'longShots', 'stamina', 'agility', 'finishing'],
    hardcodedPIs: ['move_into_channels', 'roam_from_position', 'dribble_more'],
    incompatiblePIs: ['hold_position', 'sit_narrower'],
    description: 'Gelandang tengah modern yang bergerak melebar ke half-space dan mengeksploitasi celah bek lawan.',
  },
  {
    id: 'carrilero',
    name: 'Carrilero',
    code: 'CAR',
    position: 'MC',
    availableDuties: ['Support'],
    keyAttributes: ['tackling', 'positioning', 'decisions', 'passing', 'teamwork', 'workRate', 'stamina'],
    desirableAttributes: ['anticipation', 'composure', 'firstTouch', 'marking'],
    hardcodedPIs: ['stay_wider', 'hold_position', 'fewer_risky_passes'],
    incompatiblePIs: ['get_further_forward', 'roam_from_position'],
    description: 'Gelandang perayap lateral yang mengamankan sisi sayap dan menutup celah saat bek sayap maju.',
  },

  // ================= ATTACKING MIDFIELDERS (AMC) =================
  {
    id: 'am_amc',
    name: 'Attacking Midfielder',
    code: 'AM',
    position: 'AMC',
    availableDuties: ['Support', 'Attack'],
    keyAttributes: ['passing', 'technique', 'firstTouch', 'decisions', 'vision', 'offTheBall', 'anticipation'],
    desirableAttributes: ['dribbling', 'finishing', 'longShots', 'composure', 'acceleration'],
    hardcodedPIs: ['get_further_forward'],
    incompatiblePIs: ['hold_position'],
    description: 'Nomor 10 klasik di belakang striker yang menghubungkan serangan dan mencetak gol.',
  },
  {
    id: 'ap_amc',
    name: 'Advanced Playmaker',
    code: 'AP',
    position: 'AMC',
    availableDuties: ['Support', 'Attack'],
    keyAttributes: ['vision', 'passing', 'decisions', 'composure', 'technique', 'firstTouch', 'offTheBall', 'teamwork'],
    desirableAttributes: ['agility', 'anticipation', 'dribbling', 'balance'],
    hardcodedPIs: ['roam_from_position', 'take_more_risks'],
    incompatiblePIs: ['hold_position', 'fewer_risky_passes'],
    description: 'Pusat kreativitas tim di sepertiga akhir lawan.',
  },
  {
    id: 'shadow_striker',
    name: 'Shadow Striker',
    code: 'SS',
    position: 'AMC',
    availableDuties: ['Attack'],
    keyAttributes: ['finishing', 'offTheBall', 'acceleration', 'pace', 'anticipation', 'composure', 'decisions', 'workRate'],
    desirableAttributes: ['passing', 'firstTouch', 'technique', 'dribbling', 'stamina'],
    hardcodedPIs: ['get_further_forward', 'move_into_channels', 'shoot_more_often', 'close_down_more'],
    incompatiblePIs: ['hold_position', 'fewer_risky_passes'],
    description: 'Bertindak sebagai penyerang kedua; aktif menekan dan merangsek agresif ke kotak penalti untuk gol.',
  },
  {
    id: 'enganche',
    name: 'Enganche',
    code: 'ENG',
    position: 'AMC',
    availableDuties: ['Support'],
    keyAttributes: ['passing', 'vision', 'technique', 'firstTouch', 'composure', 'decisions', 'teamwork'],
    desirableAttributes: ['anticipation', 'balance'],
    hardcodedPIs: ['hold_position', 'take_more_risks', 'dribble_less', 'close_down_less'],
    incompatiblePIs: ['get_further_forward', 'roam_from_position', 'dribble_more'],
    description: 'Playmaker statis klasik; mendistribusikan bola magis tanpa banyak berlari fisik.',
  },
  {
    id: 'trequartista_amc',
    name: 'Trequartista',
    code: 'TRE',
    position: 'AMC',
    availableDuties: ['Attack'],
    keyAttributes: ['vision', 'passing', 'technique', 'firstTouch', 'dribbling', 'offTheBall', 'decisions', 'composure', 'agility'],
    desirableAttributes: ['acceleration', 'balance', 'anticipation', 'finishing'],
    hardcodedPIs: ['roam_from_position', 'take_more_risks', 'dribble_more', 'move_into_channels', 'close_down_less'],
    incompatiblePIs: ['hold_position', 'fewer_risky_passes', 'close_down_more'],
    description: 'Seniman bebas di antara lini yang dibebaskan total dari tugas bertahan.',
  },

  // ================= WINGERS / WIDE ATTACKERS (AMR / AML) =================
  {
    id: 'winger',
    name: 'Winger',
    code: 'W',
    position: 'AMR',
    availableDuties: ['Support', 'Attack'],
    keyAttributes: ['crossing', 'dribbling', 'pace', 'acceleration', 'technique', 'agility', 'offTheBall'],
    desirableAttributes: ['passing', 'firstTouch', 'decisions', 'balance', 'workRate'],
    hardcodedPIs: ['stay_wider', 'run_wide_with_ball', 'cross_more_often'],
    incompatiblePIs: ['sit_narrower', 'cut_inside_with_ball'],
    description: 'Menyerang sisi luar pertahanan lawan dengan kecepatan tinggi dan melepaskan crossing dari byline.',
  },
  {
    id: 'inverted_winger',
    name: 'Inverted Winger',
    code: 'IW',
    position: 'AMR',
    availableDuties: ['Support', 'Attack'],
    keyAttributes: ['crossing', 'dribbling', 'passing', 'technique', 'decisions', 'offTheBall', 'pace', 'acceleration', 'agility'],
    desirableAttributes: ['vision', 'firstTouch', 'longShots', 'composure', 'finishing'],
    hardcodedPIs: ['cut_inside_with_ball', 'sit_narrower'],
    incompatiblePIs: ['stay_wider', 'run_wide_with_ball'],
    description: 'Memotong ke dalam secara diagonal menuju tepi kotak penalti untuk menembak atau mengoper terobosan.',
  },
  {
    id: 'inside_forward',
    name: 'Inside Forward',
    code: 'IF',
    position: 'AMR',
    availableDuties: ['Support', 'Attack'],
    keyAttributes: ['finishing', 'dribbling', 'pace', 'acceleration', 'offTheBall', 'decisions', 'technique', 'composure'],
    desirableAttributes: ['passing', 'firstTouch', 'crossing', 'agility', 'balance', 'longShots'],
    hardcodedPIs: ['sit_narrower', 'cut_inside_with_ball', 'shoot_more_often', 'get_further_forward'],
    incompatiblePIs: ['stay_wider', 'run_wide_with_ball'],
    description: 'Penyerang sayap pencetak gol yang langsung menusuk ke kotak penalti menyelesaikan peluang.',
  },
  {
    id: 'raumdeuter',
    name: 'Raumdeuter',
    code: 'RAU',
    position: 'AMR',
    availableDuties: ['Attack'],
    keyAttributes: ['offTheBall', 'anticipation', 'finishing', 'decisions', 'composure', 'balance'],
    desirableAttributes: ['firstTouch', 'acceleration', 'workRate', 'concentration'],
    hardcodedPIs: ['roam_from_position', 'sit_narrower', 'get_further_forward'],
    incompatiblePIs: ['hold_position', 'stay_wider'],
    description: 'Penerjemah ruang; menyelinap ke blind spot bek lawan untuk mencetak gol tap-in mematikan.',
  },

  // ================= STRIKERS (STC) =================
  {
    id: 'af',
    name: 'Advanced Forward',
    code: 'AF',
    position: 'STC',
    availableDuties: ['Attack'],
    keyAttributes: ['pace', 'acceleration', 'finishing', 'offTheBall', 'composure', 'dribbling', 'firstTouch', 'decisions'],
    desirableAttributes: ['technique', 'passing', 'heading', 'anticipation', 'agility', 'workRate'],
    hardcodedPIs: ['move_into_channels', 'dribble_more', 'shoot_more_often', 'roam_from_position'],
    incompatiblePIs: ['hold_position', 'drop_deeper'],
    description: 'Ujung tombak paling mematikan dan serbaguna; mengejar bola terobosan dan meregangkan pertahanan.',
  },
  {
    id: 'dlf',
    name: 'Deep Lying Forward',
    code: 'DLF',
    position: 'STC',
    availableDuties: ['Support', 'Attack'],
    keyAttributes: ['passing', 'technique', 'firstTouch', 'composure', 'decisions', 'teamwork', 'offTheBall', 'strength'],
    desirableAttributes: ['vision', 'finishing', 'anticipation', 'balance', 'heading'],
    hardcodedPIs: ['drop_deeper', 'hold_up_ball'],
    incompatiblePIs: ['get_further_forward'],
    description: 'Turun ke lini tengah menjemput bola, menghubungkan permainan dengan sayap atau second striker.',
  },
  {
    id: 'target_forward',
    name: 'Target Forward',
    code: 'TF',
    position: 'STC',
    availableDuties: ['Support', 'Attack'],
    keyAttributes: ['heading', 'jumpingReach', 'strength', 'bravery', 'balance', 'teamwork', 'firstTouch'],
    desirableAttributes: ['finishing', 'decisions', 'offTheBall', 'anticipation', 'aggression'],
    hardcodedPIs: ['hold_position', 'fewer_risky_passes', 'hold_up_ball'],
    incompatiblePIs: ['dribble_more', 'roam_from_position'],
    description: 'Mengandalkan keunggulan duel udara dan fisik untuk memantulkan bola bagi rekan setim.',
  },
  {
    id: 'poacher',
    name: 'Poacher',
    code: 'P',
    position: 'STC',
    availableDuties: ['Attack'],
    keyAttributes: ['finishing', 'anticipation', 'offTheBall', 'composure', 'acceleration', 'pace'],
    desirableAttributes: ['firstTouch', 'decisions', 'heading', 'agility'],
    hardcodedPIs: ['hold_position', 'shoot_more_often', 'fewer_risky_passes', 'dribble_less'],
    incompatiblePIs: ['roam_from_position', 'move_into_channels', 'take_more_risks'],
    description: 'Pemburu gol murni di kotak penalti yang hidup dari garis offside.',
  },
  {
    id: 'complete_forward',
    name: 'Complete Forward',
    code: 'CF',
    position: 'STC',
    availableDuties: ['Support', 'Attack'],
    keyAttributes: ['finishing', 'heading', 'technique', 'firstTouch', 'passing', 'decisions', 'composure', 'offTheBall', 'strength', 'jumpingReach', 'pace', 'acceleration'],
    desirableAttributes: ['vision', 'dribbling', 'teamwork', 'workRate', 'anticipation', 'agility', 'balance'],
    hardcodedPIs: ['roam_from_position', 'move_into_channels', 'take_more_risks', 'shoot_more_often', 'dribble_more'],
    incompatiblePIs: ['hold_position', 'fewer_risky_passes'],
    description: 'Penyerang sempurna yang menggabungkan teknik, fisik, kecepatan, dan insting gol kelas dunia.',
  },
  {
    id: 'pressing_forward',
    name: 'Pressing Forward',
    code: 'PF',
    position: 'STC',
    availableDuties: ['Defend', 'Support', 'Attack'],
    keyAttributes: ['workRate', 'stamina', 'aggression', 'bravery', 'teamwork', 'anticipation', 'acceleration', 'pace'],
    desirableAttributes: ['tackling', 'finishing', 'decisions', 'firstTouch', 'strength', 'composure'],
    hardcodedPIs: ['close_down_more', 'tackle_harder', 'roam_from_position'],
    incompatiblePIs: ['ease_off_tackles', 'hold_position'],
    description: 'Penyerang pekerja keras yang tanpa lelah menekan bek lawan saat menguasai bola.',
  },
  {
    id: 'false_nine',
    name: 'False Nine',
    code: 'F9',
    position: 'STC',
    availableDuties: ['Support'],
    keyAttributes: ['passing', 'vision', 'decisions', 'composure', 'technique', 'firstTouch', 'offTheBall', 'agility', 'dribbling'],
    desirableAttributes: ['finishing', 'acceleration', 'anticipation', 'balance', 'teamwork'],
    hardcodedPIs: ['drop_deeper', 'roam_from_position', 'dribble_more', 'take_more_risks'],
    incompatiblePIs: ['hold_position', 'get_further_forward'],
    description: 'Turun drastis ke lini tengah menarik bek keluar dan membuka ruang bagi sayap yang menusuk.',
  },
];

export function getRoleById(roleId: string): RoleDefinition | undefined {
  return ALL_ROLES.find(r => r.id === roleId);
}

export function getRolesByPosition(pos: string): RoleDefinition[] {
  // Posisi mapping untuk generalisasi
  if (pos === 'DL') return ALL_ROLES.filter(r => r.position === 'DR');
  if (pos === 'WBR' || pos === 'WBL') return ALL_ROLES.filter(r => r.position === 'DR');
  if (pos === 'AML') return ALL_ROLES.filter(r => r.position === 'AMR');
  if (pos === 'ML') return ALL_ROLES.filter(r => r.position === 'AMR' || r.position === 'MC');
  if (pos === 'MR') return ALL_ROLES.filter(r => r.position === 'AMR' || r.position === 'MC');
  return ALL_ROLES.filter(r => r.position === pos);
}
